CREATE TABLE adminUser(
	[adminID] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[adminName] varchar(30),
	[login] varchar(30) NULL,
	[password] varchar(30) NULL
 CONSTRAINT [PK_adminUser] PRIMARY KEY CLUSTERED 
(
	[adminID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 80) ON [PRIMARY]
) ON [PRIMARY]

GO